# Generated by Django 6.0.6 on 2026-07-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
